### ISSUE TITLE
Invalid Configuration - The configuration for the "mickgeek/yii2-daslider" component must contain a "class" element.

### ISSUE THREAD

**Issue by skapeyi** [mickgeek/yii2-daslider#2]
According to the configuration file it says
 `'mickgeek/yii2-daslider' => [
                'name' => 'mickgeek/yii2-daslider',
                'version' => '9999999-dev',
                'alias' => [
                    '@mickgeek/daslider' => $vendorDir . '/mickgeek/yii2-daslider',
                ],
            ],`
but that throws an error saying 
`The configuration for the "mickgeek/yii2-daslider" component must contain a "class" element.`

It works when you actually change `'name' => 'mickgeek/yii2-daslider',` to `'class' => 'mickgeek/yii2-daslider',`
Please update the readme

**Comment by mickgeek** [comment]
Done. Now the widget should be installed only through Composer.
